#!/bin/sh

set -e

case "$1" in
  install)
    ;;

  upgrade)
    service tomcat6 stop
    rm -rf /usr/local/tomcat6/webapps/mirebalais/
    rm -rf /usr/local/tomcat6/temp
    rm -rf /usr/local/tomcat6/work
    if [ -f /usr/local/sbin/mysqlbackup.sh ]
    then
      sh /usr/local/sbin/mysqlbackup.sh $2
    fi
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0;
