#!/bin/sh

set -e

case "$1" in
  install)
    ;;

  upgrade)
    service tomcat6 stop
    rm -rf /usr/local/tomcat6/webapps/mirebalais/
    rm -rf /usr/local/tomcat6/temp
    rm -rf /usr/local/tomcat6/work
    mysqldump -u backup -pbackup --opt --flush-logs --single-transaction openmrs | bzcat -zc > ~/openmrs_backup_$2.sql.bz2
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0;
