#!/bin/sh

set -e

case "$1" in
  configure)
    chown -R tomcat6:tomcat6 /home/tomcat6/.OpenMRS
    chown -R tomcat6:tomcat6 /usr/local/tomcat6

    if [ -n "$2" ]
    then
      #this means it's an upgrade. on clean install, we don't want to start tomcat
      service tomcat6 start
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0;
